import { Schema, model, Types } from 'mongoose'

const academicSchema = new Schema({
  idStudent: { type: Types.ObjectId, required: true, ref: 'Student' },
  year1: {
    period1: {
      lenguageAndLiterature: { type: Number, default: 0 },
      languages: { type: Number, default: 0 },
      mathematics: { type: Number, default: 0 },
      educationPhysics: { type: Number, default: 0 },
      biology: { type: Number, default: 0 },
      physics: { type: Number, default: 0 },
      chemistry: { type: Number, default: 0 },
      geography: { type: Number, default: 0 },
      stableGroup: { type: Number, default: 0 },
    },
    period2: {
      lenguageAndLiterature: { type: Number, default: 0 },
      languages: { type: Number, default: 0 },
      mathematics: { type: Number, default: 0 },
      educationPhysics: { type: Number, default: 0 },
      biology: { type: Number, default: 0 },
      physics: { type: Number, default: 0 },
      chemistry: { type: Number, default: 0 },
      geography: { type: Number, default: 0 },
      stableGroup: { type: Number, default: 0 },
    },
    period3: {
      lenguageAndLiterature: { type: Number, default: 0 },
      languages: { type: Number, default: 0 },
      mathematics: { type: Number, default: 0 },
      educationPhysics: { type: Number, default: 0 },
      biology: { type: Number, default: 0 },
      physics: { type: Number, default: 0 },
      chemistry: { type: Number, default: 0 },
      geography: { type: Number, default: 0 },
      stableGroup: { type: Number, default: 0 },
    },
  },
  year2: {
    period1: {
      lenguageAndLiterature: { type: Number, default: 0 },
      languages: { type: Number, default: 0 },
      mathematics: { type: Number, default: 0 },
      educationPhysics: { type: Number, default: 0 },
      biology: { type: Number, default: 0 },
      physics: { type: Number, default: 0 },
      chemistry: { type: Number, default: 0 },
      geography: { type: Number, default: 0 },
      stableGroup: { type: Number, default: 0 },
    },
    period2: {
      lenguageAndLiterature: { type: Number, default: 0 },
      languages: { type: Number, default: 0 },
      mathematics: { type: Number, default: 0 },
      educationPhysics: { type: Number, default: 0 },
      biology: { type: Number, default: 0 },
      physics: { type: Number, default: 0 },
      chemistry: { type: Number, default: 0 },
      geography: { type: Number, default: 0 },
      stableGroup: { type: Number, default: 0 },
    },
    period3: {
      lenguageAndLiterature: { type: Number, default: 0 },
      languages: { type: Number, default: 0 },
      mathematics: { type: Number, default: 0 },
      educationPhysics: { type: Number, default: 0 },
      biology: { type: Number, default: 0 },
      physics: { type: Number, default: 0 },
      chemistry: { type: Number, default: 0 },
      geography: { type: Number, default: 0 },
      stableGroup: { type: Number, default: 0 },
    },
  },
  year3: {
    period1: {
      lenguageAndLiterature: { type: Number, default: 0 },
      languages: { type: Number, default: 0 },
      mathematics: { type: Number, default: 0 },
      educationPhysics: { type: Number, default: 0 },
      biology: { type: Number, default: 0 },
      physics: { type: Number, default: 0 },
      chemistry: { type: Number, default: 0 },
      geography: { type: Number, default: 0 },
      stableGroup: { type: Number, default: 0 },
    },
    period2: {
      lenguageAndLiterature: { type: Number, default: 0 },
      languages: { type: Number, default: 0 },
      mathematics: { type: Number, default: 0 },
      educationPhysics: { type: Number, default: 0 },
      biology: { type: Number, default: 0 },
      physics: { type: Number, default: 0 },
      chemistry: { type: Number, default: 0 },
      geography: { type: Number, default: 0 },
      stableGroup: { type: Number, default: 0 },
    },
    period3: {
      lenguageAndLiterature: { type: Number, default: 0 },
      languages: { type: Number, default: 0 },
      mathematics: { type: Number, default: 0 },
      educationPhysics: { type: Number, default: 0 },
      biology: { type: Number, default: 0 },
      physics: { type: Number, default: 0 },
      chemistry: { type: Number, default: 0 },
      geography: { type: Number, default: 0 },
      stableGroup: { type: Number, default: 0 },
    },
  },
  year4: {
    period1: {
      lenguageAndLiterature: { type: Number, default: 0 },
      languages: { type: Number, default: 0 },
      mathematics: { type: Number, default: 0 },
      educationPhysics: { type: Number, default: 0 },
      biology: { type: Number, default: 0 },
      physics: { type: Number, default: 0 },
      chemistry: { type: Number, default: 0 },
      geography: { type: Number, default: 0 },
      stableGroup: { type: Number, default: 0 },
    },
    period2: {
      lenguageAndLiterature: { type: Number, default: 0 },
      languages: { type: Number, default: 0 },
      mathematics: { type: Number, default: 0 },
      educationPhysics: { type: Number, default: 0 },
      biology: { type: Number, default: 0 },
      physics: { type: Number, default: 0 },
      chemistry: { type: Number, default: 0 },
      geography: { type: Number, default: 0 },
      stableGroup: { type: Number, default: 0 },
    },
    period3: {
      lenguageAndLiterature: { type: Number, default: 0 },
      languages: { type: Number, default: 0 },
      mathematics: { type: Number, default: 0 },
      educationPhysics: { type: Number, default: 0 },
      biology: { type: Number, default: 0 },
      physics: { type: Number, default: 0 },
      chemistry: { type: Number, default: 0 },
      geography: { type: Number, default: 0 },
      stableGroup: { type: Number, default: 0 },
    },
  },
  year5: {
    period1: {
      lenguageAndLiterature: { type: Number, default: 0 },
      languages: { type: Number, default: 0 },
      mathematics: { type: Number, default: 0 },
      educationPhysics: { type: Number, default: 0 },
      biology: { type: Number, default: 0 },
      physics: { type: Number, default: 0 },
      chemistry: { type: Number, default: 0 },
      geography: { type: Number, default: 0 },
      stableGroup: { type: Number, default: 0 },
    },
    period2: {
      lenguageAndLiterature: { type: Number, default: 0 },
      languages: { type: Number, default: 0 },
      mathematics: { type: Number, default: 0 },
      educationPhysics: { type: Number, default: 0 },
      biology: { type: Number, default: 0 },
      physics: { type: Number, default: 0 },
      chemistry: { type: Number, default: 0 },
      geography: { type: Number, default: 0 },
      stableGroup: { type: Number, default: 0 },
    },
    period3: {
      lenguageAndLiterature: { type: Number, default: 0 },
      languages: { type: Number, default: 0 },
      mathematics: { type: Number, default: 0 },
      educationPhysics: { type: Number, default: 0 },
      biology: { type: Number, default: 0 },
      physics: { type: Number, default: 0 },
      chemistry: { type: Number, default: 0 },
      geography: { type: Number, default: 0 },
      stableGroup: { type: Number, default: 0 },
    },
  },
})

export const NoteModel = model('Note', academicSchema)
