PUT  http://localhost:3000/student/684b085b535117d5c6a954ff
User-Agent: rest-client
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MzYyYWYwZjMxYzYwZDQ1MTZiZTAwYiIsImlhdCI6MTc0ODgzNTY0MCwiZXhwIjoxNzQ4ODM5MjQwfQ.aoXPDwPR3UIyns0flkmYTiW3cnfV5BA_mYKkp0DhKMA

{
    "names": "Toto calss",
    "lastnames": "Test test"
}